apiVersion: v1
kind: Service
metadata:
    name: blogdb-service
    labels:
        app: blogdb-postgres
spec:
    type: ClusterIP
    ports:
        - port: 8081
          targetPort: 80
    selector:
        app: blogdb-postgres
