apiVersion: v1
kind: Service
metadata:
    name: blog-ui-service
spec:
    type: NodePort
    ports:
        - protocol: TCP
          nodePort: 30003
          port: 8080
          targetPort: 5000
    selector:
        app: blog-ui
