apiVersion: v1
kind: Service
metadata:
    name: blogdb-service
    labels:
        app: blogdb-postgres
spec:
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 5000
    selector:
        app: blogdb-postgres
