apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api-container
        image: localhost:32000/flask-api
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          # - name: SERVICE_POSTGRES_SERVICE_HOST
            # value: service-postgres.default.svc.cluster.local
          - name: POSTGRES_DB_USER
            valueFrom:
              secretKeyRef:
                name: blogdb-secret
                key: POSTGRES_USER
          - name: POSTGRES_DB_PSW
            valueFrom:
              secretKeyRef:
                name: blogdb-secret
                key: POSTGRES_PASSWORD
