apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-api-test-deployment
  labels: 
    app: project-api-test
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: project-api-test
  template:
    metadata:
      labels:   
        app: project-api-test
    spec: 
      containers: 
      - name: project-api-test-container
        image: localhost:32000/project-api-test 
        ports: 
        - containerPort: 80
        env: 
          # - name: SERVICE_POSTGRES_SERVICE_HOST
            # value: service-postgres.default.svc.cluster.local
          - name: POSTGRES_DB_USER
            valueFrom: 
              secretKeyRef:
                name: blogdb-secret
                key: POSTGRES_USER
          - name: POSTGRES_DB_PSW
            valueFrom: 
              secretKeyRef:
                name: blogdb-secret
                key: POSTGRES_PASSWORD
