apiVersion: v1
kind: Service
metadata: 
  name: project-api-test-service
spec: 
  type: NodePort 
  ports: 
  - protocol: TCP 
    nodePort: 30005
    port: 5000
    targetPort: 5000
  selector: 
    app: project-api-test